<?php

namespace Database\Seeders;

use App\Models\HsReferido;
use Illuminate\Database\Seeder;

class HsReferidosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        HsReferido::create(['correo' => '0','nombre' => 'Otros','tipo' =>'Otros']);
        HsReferido::create(['correo' => '','nombre' => 'Otros','tipo' =>'Otros']);
        HsReferido::create(['correo' => 'aambrosini@sefarvzla.com','nombre' => 'Abel Andrea Ambrosini','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'avillasmil@sefarvzla.com','nombre' => 'Adela Villasmil','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Adriana Algarra','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'aizaguirre@sefarvzla.com','nombre' => 'Adriana María Izaguirre Lujan','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'acastro@sefarvzla.com','nombre' => 'Alejandra Castro Godard','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Alejandra Castrov Godard','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'agoiticoa@sefarvzla.com','nombre' => 'Alex Goiticoa González','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'apieve@sefarvzla.com','nombre' => 'Alexandra Pieve','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'asucre@sefarvzla.com','nombre' => 'Alvaro Felipe Sucre Guruceaga','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'seguridad+familiares@sefarvzla.com','nombre' => 'Amigo, conocido o familiares','tipo' =>'Amigos']);
        HsReferido::create(['correo' => 'adominguez@sefarvzla.com','nombre' => 'Ana Carolina Domínguez Jurado','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'arincon@sefarvzla.com','nombre' => 'Ana Isabel Rincón Herrera','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Ana Laura García Hernández','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'a.delgado@sefarvzla.com','nombre' => 'Ana María Delgado','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'aduque@sefarvzla.com','nombre' => 'Ana María Duque','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'asotelo@sefarvzla.com','nombre' => 'Ana Sotelo Alonso','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'aparis@sefarvzla.com','nombre' => 'Ana Virginia París Montesinos','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Analista de ventas','tipo' =>'Otros']);
        HsReferido::create(['correo' => '','nombre' => 'Andreina Diaz Gonzalez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Andreina Diaz González','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Andreina Lozada Escalona','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'amarquez@sefarvzla.com','nombre' => 'Andreína Márquez Gómez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'amonroy@sefarvzla.com','nombre' => 'Angelica Monroy','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Annerys Andreina Osmi Carvajal','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Antonella Di Miele de González','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'seguridad+buscadores@sefarvzla.com','nombre' => 'Anuncio en Buscadores','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'aalfaro@sefarvzla.com','nombre' => 'Any Alfaro','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'aranzazu.rodriguez@sefarvzla.com','nombre' => 'Aranzazu Rodríguez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Ariela Camhi Wolf','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Badell Law','tipo' =>'Bufetes']);
        HsReferido::create(['correo' => '','nombre' => 'Beatriz Grau','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Carlos Gustavo Bacalao Arenas','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'c.izurieta@sefarvzla.com','nombre' => 'Carlos Simón Izurieta Galán','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Carlos Simón Izurieta Galán.','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'cguerrero@sefarvzla.com','nombre' => 'Carolina Guerrero Villegas','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'cpacheco@sefarvzla.com','nombre' => 'Carolina Pacheco Alvarado','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'c.alcantara@sefarvzla.com','nombre' => 'Celeste Alcantara','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Celeste Alcántara','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'charlie.teran@sefarvzla.com','nombre' => 'Charlie Omar Teran Arocha','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Claudia Jiménez Mac Gregor','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Claudia Sofia Ramos Gonzalez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Claudia Sofia Ramos González','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'COORDINADOR','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Cora Chumaceiro','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'cora.diaz@sefarvzla.com','nombre' => 'Cora Diaz','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Cora Diaz de Chumaceiro','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'dgarcia@sefarvzla.com','nombre' => 'Dangmar García de Segnini','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Dangmar Teresa García de Segnini','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'dcasseres@sefarvzla.com','nombre' => 'Daniela Casseres','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'dgutierrez@sefarvzla.com','nombre' => 'Dayvelis Gutierrez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'dcolmenares@sefarvzla.com','nombre' => 'Dexy Yanira Colmenares Molina','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'diglesias@sefarvzla.com','nombre' => 'Dian Vanessa Iglesias Diaz','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'etinoco@sefarvzla.com','nombre' => 'Elizabeth Tinoco','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'echacon@sefarvzla.com','nombre' => 'Esperanza Lourdes Chacón Valecillos','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'ediaz@sefarvzla.com','nombre' => 'Ester de Lourdes Diaz Cataldo','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Fatima Regina Vivas Martínez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Félix Noe Penagos Madrigal','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'fduncan@sefarvzla.com','nombre' => 'Frank Manuel Duncan Fajardo','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'gmizrachi@sefarvzla.com','nombre' => 'Gabriela Margarita Mizrachi Recagno','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Gaby Paoli','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Genealogista','tipo' =>'Otros']);
        HsReferido::create(['correo' => 'germanfleitas@sefarvzla.com','nombre' => 'German Rafael Fleitas Freites','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'ghiggins@sefarvzla.com','nombre' => 'Gerson Higgins','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Gianfranco Cesario Rojas','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Giannina Mangles','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'garanda@sefarvzla.com','nombre' => 'Gisela Irene Aranda Hermida','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'seguridad+google@sefarvzla.com','nombre' => 'Google','tipo' =>'Google']);
        HsReferido::create(['correo' => '','nombre' => 'Haydeé Tivisay Rendón Cardozo','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'gerenciadeventas@sefarvzla.com','nombre' => 'Heylamar Ramos','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Hugo Jimenez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'irodriguez@sefarvzla.com','nombre' => 'Ingrid Cecilia Rodriguez Valderrama','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Irma Lucia Renzulli Gomez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Isabel Cristina Martinez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'iardila@sefarvzla.com','nombre' => 'Ivette Ardila','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Jhefferson Ladera','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Joanna Alexandra Gutierrez Leon','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Joanna Gutierrez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'josealejandro.perez@sefarvzla.com','nombre' => 'José Alejandro Pérez Altuve','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jquinones@sefarvzla.com','nombre' => 'Jose Angel Quiñones Laffont','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'José Antonio Olavarrieta','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Jose Luis Romero','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'José Luis Romero Flórez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jmraposo@sefarvzla.com','nombre' => 'Jose Manuel Raposo Alfonso','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'José Manuel Raposo Alfonso','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Josefina Uzcátegui Añez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Juan Carlos Duque','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'admin.ventas@sefarvzla.com','nombre' => 'Juan Carlos Rondón','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Juan Carlos Senior','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jmartin@sefarvzla.com','nombre' => 'Juanita Martín Ortiz','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jrondon@sefarvzla.com','nombre' => 'Judith Josefina Rondón González','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jpinto@sefarvzla.com','nombre' => 'Julio Cesar Pinto Maldonado','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Keyla Veronica Romero Aguilar','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Laureana Melchor','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Leonor Giménez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'libsen.rodriguez@sefarvzla.com','nombre' => 'Libsen Rodríguez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Libsen Rodríguez Gabaldón','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Liliana Mercedes Vásquez de Do Couto','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'lcepero@sefarvzla.com','nombre' => 'Livia Adriana Cepero','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'lgarlin@sefarvzla.com','nombre' => 'Luis Enrique Garlin Garcia','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Luis Enrique Garlin García','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'luis.martinez@sefarvzla.com','nombre' => 'Luis Martínez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Luisa Abad','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'Luisa Barrios','nombre' => 'Luisa Barrios','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'lbustamante@sefarvzla.com','nombre' => 'Luisa Mercedes Bustamante de Echegarreta','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'ltamayo@sefarvzla.com','nombre' => 'Luisa Mercedes Tamayo Briceño','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'marco.pulgar@sefarvzla.com','nombre' => 'Marco Pulgar','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Margaret Ramos','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mramos@sefarvzla.com','nombre' => 'Margareth Ramos','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mvasquez@sefarvzla.com','nombre' => 'María Alejandra Vázquez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Beatriz Lopez Consalvi','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Beatriz López Consalvi','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Carolina Carbonara','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mhernandez@sefarvzla.com','nombre' => 'María Carolina Hernandez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Carolina Hernández','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mbello@sefarvzla.com','nombre' => 'Maria Cecilia Bello','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Cecilia Bello','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Maria Cecilia Febres','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Maria Cecilia Febres Cordero','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mmiguez@sefarvzla.com','nombre' => 'Maria Consuelo Miguez Gonzalez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Delfina Otamendi Erminy','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mcruz@sefarvzla.com','nombre' => 'María Gracia Cruz Añez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mgimenez@sefarvzla.com','nombre' => 'Maria Irene Gimenez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mchavez@sefarvzla.com','nombre' => 'María Luisa Chávez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Luisa Chávez -Rosales -Hurtado','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mparedes@sefarvzla.com','nombre' => 'Maria Luisa Paredes','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Luisa Paredes','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Nevett Gimón.','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mbriceno@sefarvzla.com','nombre' => 'Maria Soledad Briceño','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Soledad Briceño','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Susana Chalbaud','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mmucino@sefarvzla.com','nombre' => 'Maria Teresa Muciño','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'María Teresa Muciño','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mzapata@sefarvzla.com','nombre' => 'Maria Zapata','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'marianela.ramos@sefarvzla.com','nombre' => 'Marianela Ramos','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mstredel@sefarvzla.com','nombre' => 'Mariangel Stredel','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mvallejo@sefarvzla.com','nombre' => 'Mariangela Vallejo Galindo','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mnarvaez@sefarvzla.com','nombre' => 'Marina Narvaez Uroz','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'm.moreno@sefarvzla.com','nombre' => 'Marisol Moreno González','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Marivi Frias','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Marivi Frías','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mcortinas@sefarvzla.com','nombre' => 'Martha Cortiñas Márquez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'mbriceno@sefarvzla.com','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'MG Tours','tipo' =>'Bufetes']);
        HsReferido::create(['correo' => 'mireya.bustamante@sefarvzla.com','nombre' => 'Mireya Bustamante','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'm.narvaez@sefarvzla.com','nombre' => 'Miriam Mercedes Narváez Monagas','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Morela Scull','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mscull@sefarvzla.com','nombre' => 'Morella Scull','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mycabogados@sefarvzla.com','nombre' => 'Mujica y Coto Abogados','tipo' =>'Bufetes']);
        HsReferido::create(['correo' => '','nombre' => 'Myriam Camhi Wolf','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'nlinares@sefarvzla.com','nombre' => 'Neira María Linares / Eduardo Gomez Parra','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Neira María Linares/Eduardo Gomez Parra','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Nelly Coromoto Gonzalez Paoli','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Nelly Coromoto González Paoli','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Nelly Coromoto González Paoli.','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Nere Pinerua','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'NULL','nombre' => 'NULL','tipo' =>'Otros']);
        HsReferido::create(['correo' => 'orios@sefarvzla.com','nombre' => 'Orlando Jose Rios Chaves','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'oclavijo@sefarvzla.com','nombre' => 'Oscar Clavijo Camero','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'ocastro@sefarvzla.com','nombre' => 'Oscar Enrique Castro Rodriguez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'seguridad+otros@sefarvzla.com','nombre' => 'Otros','tipo' =>'Otros']);
        HsReferido::create(['correo' => '','nombre' => 'P & V Abogados','tipo' =>'Bufetes']);
        HsReferido::create(['correo' => '','nombre' => 'Pagina Web','tipo' =>'Otras redes sociales']);
        HsReferido::create(['correo' => 'pvargas@sefarvzla.com','nombre' => 'Patricia Vargas Sequera','tipo' =>'Bufetes']);
        HsReferido::create(['correo' => 'rpina@sefarvzla.com','nombre' => 'Ramón Eduardo Piña Padrón','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'rlopez@sefarvzla.com','nombre' => 'Raquel del Carmen López Sánchez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'seguridad+rrss@sefarvzla.com','nombre' => 'Redes Sociales','tipo' =>'Otras redes sociales']);
        HsReferido::create(['correo' => 'rguillen@sefarvzla.com','nombre' => 'Robert Samuel Guillen Hernandez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'rorozco@sefarvzla.com','nombre' => 'Roberto Enrique Orozco Zuleta','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'rrincon@sefarvzla.com','nombre' => 'Roberto Rincon','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Rodrigo Ramos','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'rgonzalez@sefarvzla.com','nombre' => 'Rosa Ysela González Evora','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Rosanna Stefani','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'rportillo@sefarvzla.com','nombre' => 'Ruth Portillo','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'svalles@sefarvzla.com','nombre' => 'Sailé María Vallés Tovar','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Sarah Camhi Wolf','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'SEFAR: Transformando Vidas','tipo' =>'Ventas']);
        HsReferido::create(['correo' => '','nombre' => 'Silvana María Malabet Juliao','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'sperez@sefarvzla.com','nombre' => 'Silvana Pérez Caressi','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'gerenciav@sefarvzla.com','nombre' => 'Sobeida Infante','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Social Media','tipo' =>'Otras redes sociales']);
        HsReferido::create(['correo' => '','nombre' => 'Soledad Sánchez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Sotillo & Asociados','tipo' =>'Bufetes']);
        HsReferido::create(['correo' => '','nombre' => 'Stella Camposano','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Stephany Andrea De Silva','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'sdesilva@sefarvzla.com','nombre' => 'Stephany De Silva','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Susan Herrera','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'susana.paoli@sefarvzla.com','nombre' => 'Susana Paoli','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'tfarreras@sefarvzla.com','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'tfarreras@sefarvzla.com','nombre' => 'Tibisay De La Trinidad Farreras Rodriguez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'tevans@sefarvzla.com','nombre' => 'Travieso Evans','tipo' =>'Bufetes']);
        HsReferido::create(['correo' => '','nombre' => 'Valeria Oriana Moser Fuentes','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'valandete@sefarvzla.com','nombre' => 'Vanesa Alandete','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'veronica.poletto@sefarvzla.com','nombre' => 'Veronica Poletto','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'vmoser@sefarvzla.com','nombre' => 'Veronica Victoria Moser Fuentes','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'vcarrillo@sefarvzla.com','nombre' => 'Virginia Maria Del Carmen Carrillo Batalla','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Whitney Perea','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'yperez@sefarvzla.com','nombre' => 'Yajaira del Carmen Pérez Cantor','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'yeinsondiaz@sefarvzla.com','nombre' => 'Yeinson Diaz','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Yeinson Díaz','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => '','nombre' => 'Zayda Romero','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'zpina@sefarvzla.com','nombre' => 'Zayda Romero & Rafael Ramones','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'Zullibeth Marimon','nombre' => 'Zullibeth Marimon','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'dcourt@sefarvzla.com','nombre' => 'Daniela Alejandra Court Aguiar','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'Otros','nombre' => 'Otros','tipo' =>'Otros']);
        HsReferido::create(['correo' => 'vrondon@sefarvzla.com','nombre' => 'Vivian Rondón','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'Vivian Rondon','nombre' => 'Vivian Rondon','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'taldana@sefarvzla.com','nombre' => 'Tania Aldana','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'crisantoantonio@sefarvzla.com','nombre' => 'Crisanto Bello','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'operacionesv@sefarvzla.com','nombre' => 'Operaciones Venezuela','tipo' =>'Otros']);
        HsReferido::create(['correo' => 'aibarra@sefarvzla.com','nombre' => 'Abraham Ibarra','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'apila@sefaruniversal.eu','nombre' => 'Adrialis Milagros Pila Escalona','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'aberrizbeitia@sefarvzla.com','nombre' => 'Alberto Berrizbeitia','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'aguerra@sefarvzla.com','nombre' => 'Alejandra Guerra','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'arincon@sefarvzla.com','nombre' => 'Ana Isabel Rincon','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'acarrasquero@sefarvzla.com','nombre' => 'Andreina Carrasquero','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'amartinez@sefarvzla.com','nombre' => 'Andreina Martinez Salaverria','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'acera@sefarvzla.com','nombre' => 'Arlet Patricia Cera Avendaño','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'crojas@sefarvzla.com','nombre' => 'Carlos Alberto Rojas Rodriguez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'cdominguez@sefarvzla.com','nombre' => 'Carlos Dominguez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'cguilliano@sefaruniversal.eu','nombre' => 'Carolina Guilliano','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'cduran@sefarvzla.com','nombre' => 'Catalina Duran Chahin','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'ctorres@sefarvzla.com','nombre' => 'Clemencia Torres','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'cbonora@sefarvzla.com','nombre' => 'Cristina Bonora Buzzoni','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'dcoronado@sefarvzla.com','nombre' => 'Dagoberto Coronado Vivas','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'dcasseres@sefarvzla.com','nombre' => 'Daniela Patricia Casseres Estarita','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'ddiaz@sefarvzla.com','nombre' => 'Dayana Paola Díaz Pérez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'dgutierrez@sefarvzla.com','nombre' => 'Dayvelis Carolina Gutiérrez Rodríguez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'donosoyasociados@sefarvzla.com','nombre' => 'Donoso &amp; Asociados','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'coordinadorlogistico@sefarvzla.com','nombre' => 'Duvan Enrique Guzmán Chiquillo','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'equintero@sefarvzla.com','nombre' => 'Edier Quintero','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'ehernandez@sefarvzla.com','nombre' => 'Elayne Hernández Añez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'eschmid@sefarvzla.com','nombre' => 'Erika Schmid','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'fpastrana@sefarvzla.com','nombre' => 'Fanny Pastrana Celis','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'fgonzalez@sefarvzla.com','nombre' => 'Felipe González','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'gmorales@sefarvzla.com','nombre' => 'Gabriela Morales','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'gbolivar@sefarvzla.com','nombre' => 'Giselle Bolivar','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'ganez@sefarvzla.com','nombre' => 'Gustavo Alberto Añez Serpa (MG Tours)','tipo' =>'Bufetes']);
        HsReferido::create(['correo' => 'hbozo@sefarvzla.com','nombre' => 'Humberto Francisco Bozo Ramirez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'imartinez@sefarvzla.com','nombre' => 'Isabel Cristina Martinez de Penzini','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jzavala@sefarvzla.com','nombre' => 'Jeiser Zavala','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jmarcano@sefarvzla.com','nombre' => 'Jeissy Marcano','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jujueta@sefarvzla.com','nombre' => 'Jennifer Stefania Ujueta González','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jortiz@sefarvzla.com','nombre' => 'Jesica Ortiz','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jfonseca@sefarvzla.com','nombre' => 'Jhon Fonseca','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jopinero@sefarvzla.com','nombre' => 'Johana Carolina Piñero Moreno','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jaguilar@sefarvzla.com','nombre' => 'José Aguilar','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'jvasco@sefarvzla.com','nombre' => 'Juana María Vasco Moscovitz','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'kmadachi@sefarvzla.com','nombre' => 'Katherine Lizeth Madachi Altamar','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'lolarte@sefarvzla.com','nombre' => 'Laura María Olarte Zúñiga','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'lmelchor@sefarvzla.com','nombre' => 'Laurana Melchor','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'ltorregrosa@sefarvzla.com','nombre' => 'Ledis Torregrosa','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'lbedoya@sefarvzla.com','nombre' => 'Luis Felipe Bedoya','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'ldiaz@sefarvzla.com','nombre' => 'Luisa Diaz','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'lbarrios@sefarvzla.com','nombre' => 'Luisa Fernanda Barrios Castillo','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'lcardenas@sefarvzla.com','nombre' => 'Luz Cardenas','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mhait@sefarvzla.com','nombre' => 'Marcelo Hait','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mperez@sefarvzla.com','nombre' => 'Maria Luisa Perez Frontado','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mnavarro@sefarvzla.com','nombre' => 'Maria Navarro','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mnoda@sefarvzla.com','nombre' => 'Maria Noda','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mrajbe@sefarvzla.com','nombre' => 'Maria Rajbe','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mbaquero@sefarvzla.com','nombre' => 'Martha Baquero','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mgiffoni@sefarvzla.com','nombre' => 'María Alejandra Giffoni Barraez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mardila@sefarvzla.com','nombre' => 'María Camila Ardila Barrios','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'marbelaez@sefarvzla.com','nombre' => 'María del Rosario Arbeláez Lozano','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mgonzalez@sefarvzla.com','nombre' => 'Moises González','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'mpuello@sefarvzla.com','nombre' => 'Myrna Puello','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'asist.juridico@sefarvzla.com','nombre' => 'Nathaly León','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'nreyes@sefarvzla.com','nombre' => 'Nicolas Reyes','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'Peñalvert &amp; Asociados','nombre' => 'Peñalvert & Asociados','tipo' =>'Bufetes']);
        HsReferido::create(['correo' => 'rgimenez@sefarvzla.com','nombre' => 'Ricardo Gimenez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'rblanco@sefarvzla.com','nombre' => 'Rogelio Blanco','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'rstefani@sefarvzla.com','nombre' => 'Rossana Stefani','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 's.sanchez@sefarvzla.com','nombre' => 'Sandra Milena Sánchez Álfaro','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'sbernal@sefarvzla.com','nombre' => 'Sandra Patricia Bernal Martínez','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'acontable@sefarvzla.com','nombre' => 'Shirley Traslaviña','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'alfredo.machado@somaconsultores.com','nombre' => 'Soma Consultores//Alfredo Machado','tipo' =>'Bufetes']);
        HsReferido::create(['correo' => 'siperez@sefarvzla.com','nombre' => 'Sonia Isabel Pérez Doria','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'sguio@sefarvzla.com','nombre' => 'Suly Del Carmen Guio Vega','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'valandete@sefarvzla.com','nombre' => 'Vanessa Alandete','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'asistentepresidencial@sefarvzla.com','nombre' => 'Viviana Castro','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'wlegonia@sefarvzla.com','nombre' => 'Wilfredo Legonia','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'alex.veroes@sefarvzla.com','nombre' => 'Yusberth Veroes Ruiz','tipo' =>'Coordinadores']);
        HsReferido::create(['correo' => 'zromero@sefarvzla.com','nombre' => 'Zayda Romero & Rafael Ramones','tipo' =>'Bufetes']);
        HsReferido::create(['correo' => 'zmarimon@sefarvzla.com','nombre' => 'Zullibeth Marimon','tipo' =>'Coordinadores']);
    }
}
