@extends('adminlte::page')

@section('title', $campaign->name)

@section('content_header')
    <div class="d-flex justify-content-between align-items-center"><div><h1 class="mb-0">{{ $campaign->name }}</h1><small class="text-muted">{{ $campaign->subject }} · {{ $campaign->list?->name }}</small></div><div><a href="{{ route('marketing.dashboard') }}" class="btn btn-outline-secondary">Panel</a>@if(in_array($campaign->status, ['draft','scheduled','paused'])) <a href="{{ route('marketing.campaigns.edit', $campaign) }}" class="btn btn-outline-primary">Editar</a> @endif</div></div>
@stop

@section('content')
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
    <div class="row">@foreach(['total' => ['Destinatarios', 'secondary'], 'sent' => ['Enviados', 'primary'], 'delivered' => ['Entregados', 'success'], 'opened' => ['Aperturas únicas', 'info'], 'clicked' => ['Clics únicos', 'warning'], 'bounced' => ['Rebotes', 'danger']] as $key => [$label, $color])<div class="col-lg-2 col-md-4 col-6"><div class="small-box bg-{{ $color }}"><div class="inner"><h3>{{ number_format($analytics[$key]) }}</h3><p>{{ $label }}</p></div></div></div>@endforeach</div>
    <div class="row"><div class="col-lg-8"><div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title">Rendimiento</h3></div><div class="card-body"><div class="row text-center"><div class="col-md-3"><strong>{{ $analytics['sent'] ? number_format($analytics['delivered'] / $analytics['sent'] * 100, 1) : 0 }}%</strong><br><small>tasa de entrega</small></div><div class="col-md-3"><strong>{{ $analytics['delivered'] ? number_format($analytics['opened'] / $analytics['delivered'] * 100, 1) : 0 }}%</strong><br><small>tasa de apertura</small></div><div class="col-md-3"><strong>{{ $analytics['delivered'] ? number_format($analytics['clicked'] / $analytics['delivered'] * 100, 1) : 0 }}%</strong><br><small>tasa de clic</small></div><div class="col-md-3"><strong>{{ $analytics['sent'] ? number_format($analytics['bounced'] / $analytics['sent'] * 100, 1) : 0 }}%</strong><br><small>tasa de rebote</small></div></div><hr><p class="mb-0 text-muted">{{ number_format($analytics['open_events']) }} aperturas y {{ number_format($analytics['click_events']) }} clics registrados en total; {{ number_format($analytics['unsubscribed']) }} bajas y {{ number_format($analytics['complained']) }} quejas.</p></div></div></div>
    <div class="col-lg-4"><div class="card card-outline card-secondary"><div class="card-header"><h3 class="card-title">Enviar</h3></div><div class="card-body">@if($campaign->status === 'sending')<form method="POST" action="{{ route('marketing.campaigns.pause', $campaign) }}">@csrf<button class="btn btn-warning btn-block" onclick="return confirm('¿Pausar los destinatarios que sigan pendientes?')"><i class="fas fa-pause mr-1"></i>Pausar envío</button></form>@elseif(in_array($campaign->status, ['draft','scheduled','paused']))<form method="POST" action="{{ route('marketing.campaigns.send', $campaign) }}">@csrf<button class="btn btn-success btn-block" onclick="return confirm('¿Encolar el envío a toda la lista?')"><i class="fas fa-paper-plane mr-1"></i>{{ $campaign->status === 'paused' ? 'Reanudar envío' : 'Enviar a la lista' }}</button></form><hr><form method="POST" action="{{ route('marketing.campaigns.test', $campaign) }}">@csrf<div class="form-group"><label>Enviar prueba por SES</label><input required type="email" name="email" class="form-control" placeholder="tu@correo.com"></div><button class="btn btn-outline-primary btn-block">Enviar prueba</button></form>@else<p class="mb-0">Estado: <span class="badge badge-primary">{{ ucfirst($campaign->status) }}</span></p>@endif</div></div></div></div>
    <div class="card card-outline card-secondary"><div class="card-header"><h3 class="card-title">Eventos recientes</h3></div><div class="card-body p-0 table-responsive"><table class="table table-sm table-hover mb-0"><thead><tr><th>Fecha</th><th>Evento</th><th>Destinatario</th></tr></thead><tbody>@forelse($events as $event)<tr><td>{{ optional($event->occurred_at)->format('d/m/Y H:i:s') }}</td><td><span class="badge badge-light text-uppercase">{{ $event->event_type }}</span></td><td>{{ $event->recipient?->email ?? '—' }}</td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-3">Aún no hay eventos.</td></tr>@endforelse</tbody></table></div>@if($events->hasPages())<div class="card-footer">{{ $events->links() }}</div>@endif</div>
@stop
