<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('negocios', function (Blueprint $table) {
            $table->id();
            $table->text("abogado___asesor__clonada_")->nullable();
            $table->text("analista_de_ventas")->nullable();
            $table->text("apellidos_del_cliente")->nullable();
            $table->json("argumento_de_ventas__new_")->nullable();
            $table->date("autorizacion___cuestionario")->nullable();
            $table->text("carta_nat_pagado")->nullable();
            $table->text("carta_nat_preestab")->nullable();
            $table->text("cil___fcje_pagado")->nullable();
            $table->text("cil___fcje_preestab")->nullable();
            $table->integer("cliente__numero")->nullable();
            $table->text("codigo_de_proceso")->nullable();
            $table->text("df_billing_contact")->nullable();
            $table->text("df_currency")->nullable();
            $table->text("df_discount_code")->nullable();
            $table->text("df_mode")->nullable();
            $table->text("df_order_id")->nullable();
            $table->text("df_payment_method")->nullable();
            $table->text("df_payment_processor")->nullable();
            $table->text("df_payment_status")->nullable();
            $table->text("df_payment_type")->nullable();
            $table->text("df_product_name")->nullable();
            $table->integer("df_quantity")->nullable();
            $table->text("df_source")->nullable();
            $table->text("df_subscription_frequency")->nullable();
            $table->integer("df_tax_amount")->nullable();
            $table->integer("df_tax_rate")->nullable();
            $table->date("documentacion_fase_1_solicitada")->nullable();
            $table->date("documentacion_fase_2_solicitada")->nullable();
            $table->date("documentacion_fase_3_solicitada")->nullable();
            $table->json("documentos")->nullable();
            $table->text("enlace_proyecto__documentacion_")->nullable();
            $table->date("enviado_a_pago_de_tasas")->nullable();
            $table->text("estatus__genealogia")->nullable();
            $table->text("estatus_proceso")->nullable();
            $table->text("etiquetas")->nullable();
            $table->integer("fase_0_pagado")->nullable();
            $table->text("fase_0_pagado__teamleader_")->nullable();
            $table->text("fase_1_pagado")->nullable();
            $table->text("fase_1_pagado__teamleader_")->nullable();
            $table->text("fase_1_preestab")->nullable();
            $table->text("fase_2_pagado")->nullable();
            $table->text("fase_2_pagado__teamleader_")->nullable();
            $table->text("fase_2_preestab")->nullable();
            $table->text("fase_3_pagado")->nullable();
            $table->text("fase_3_pagado__teamleader_")->nullable();
            $table->text("fase_3_preestab")->nullable();
            $table->text("fcje_pagado")->nullable();
            $table->text("fcje_preestab")->nullable();
            $table->date("fecha_de_aceptacion")->nullable();
            $table->date("fecha_de_cobro")->nullable();
            $table->text("fecha_de_confirmacion_del_cliente_como_recibido__juramentacion_")->nullable();
            $table->date("fecha_de_nacimiento")->nullable();
            $table->text("fecha_de_notificacion_al_cliente_por_email__juramentacion_")->nullable();
            $table->date("fecha_de_rechazo")->nullable();
            $table->date("fecha_de_resolucion")->nullable();
            $table->date("fecha_en_la_que_se_anadio")->nullable();
            $table->date("fecha_fase_0_pagado")->nullable();
            $table->date("fecha_fase_1_pagado")->nullable();
            $table->date("fecha_fase_2_pagado")->nullable();
            $table->date("fecha_fase_3_pagado")->nullable();
            $table->date("formalizacion_d__judicial")->nullable();
            $table->date("formalizacion_r__alzada")->nullable();
            $table->text("fuente_teamleader")->nullable();
            $table->boolean("genealogia_aprobada")->nullable();
            $table->integer("id_del_contacto_asociado")->nullable();
            $table->text("mas_informacion")->nullable();
            $table->text("migrado_desde_tl__sistemas_")->nullable();
            $table->integer("monto_fase_1_pagado")->nullable();
            $table->integer("monto_fase_2_pagado")->nullable();
            $table->integer("monto_fase_3_pagado")->nullable();
            $table->text("motivo_del_rechazo__explicacion_")->nullable();
            $table->date("n10__fecha_asignacion_de_juez")->nullable();
            $table->text("n10__justificante_de_formalizacion__enlace_")->nullable();
            $table->date("n11__envio_redaccion_abogada")->nullable();
            $table->text("n12__notas___no__expediente")->nullable();
            $table->date("n13__fecha_recurso_alzada")->nullable();
            $table->date("n1__enviada_al_cliente")->nullable();
            $table->date("n1__fecha_de_registro_fcje")->nullable();
            $table->text("n1__lugar_del_expediente")->nullable();
            $table->text("n1__monto_preestablecido")->nullable();
            $table->json("n2__antecedentes_penales")->nullable();
            $table->text("n2__ciudad_formalizacion")->nullable();
            $table->date("n2__enviado_a_redaccion_informe")->nullable();
            $table->date("n2__firmado_por_el_cliente")->nullable();
            $table->text("n2__monto_pagado")->nullable();
            $table->text("n3__contratos_y_permisos")->nullable();
            $table->date("n3__f__vencimiento_ant__penal")->nullable();
            $table->date("n3__gestionado___entregado")->nullable();
            $table->date("n3__informe_cargado")->nullable();
            $table->date("n4__certificado_descargado")->nullable();
            $table->date("n4__f__venci__antec__penal_otro")->nullable();
            $table->text("n4__notario___abogado")->nullable();
            $table->text("n4__pago_tasa")->nullable();
            $table->date("n5___f_solicitud_documentos")->nullable();
            $table->date("n5__fecha_de_formalizacion")->nullable();
            $table->text("n5__notas_genealogia")->nullable();
            $table->date("n6__cil_preaprobado")->nullable();
            $table->date("n6__f_venci_p_n_apostilla")->nullable();
            $table->date("n6__fecha_acta_remitida_")->nullable();
            $table->date("n7__enviado_al_dto_juridico")->nullable();
            $table->date("n7__fecha_caducidad_pasaporte")->nullable();
            $table->date("n7__fecha_de_resolucion")->nullable();
            $table->date("n8__f_rec__solicitud_doc")->nullable();
            $table->date("n91__recepcion_recaudos_fisico")->nullable();
            $table->date("n9__enviado_a_legales")->nullable();
            $table->date("n9__notif__1__int__subsanar_")->nullable();
            $table->text("no__pasaporte")->nullable();
            $table->integer("no_de_proyecto_tl")->nullable();
            $table->text("nombre_cliente")->nullable();
            $table->integer("numero")->nullable();
            $table->text("numero_de_telefono")->nullable();
            $table->text("numero_de_telefono_movil")->nullable();
            $table->text("origen")->nullable();
            $table->text("pago_cupon")->nullable();
            $table->integer("pago_registro")->nullable();
            $table->text("proyecto")->nullable();
            $table->text("proyecto_tl")->nullable();
            $table->text("representante_legal")->nullable();
            $table->text("se_trabaja_desde")->nullable();
            $table->text("servicio_solicitado")->nullable();
            $table->text("servicio_solicitado2")->nullable();
            $table->text("supervisor_de_ventas")->nullable();
            $table->date("tasa_pagada")->nullable();
            $table->text("hubspot_id")->nullable();
            $table->text("teamleader_id")->nullable();
            $table->integer("user_id")->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('negocios');
    }
};
