<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Ejecutar la migración.
     */
    public function up(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->text('aacs_madre')->nullable();
            $table->text('aacs_padre')->nullable();
            $table->text('acta_de_divorcio')->nullable();
            $table->text('address')->nullable();
            $table->text('adjuntar_archivo_de_comprobante_de_pago')->nullable();
            $table->text('anos_en_residencia_actual')->nullable();
            $table->text('antecedentes_penales_apostillada')->nullable();
            $table->text('apellido_de_casada')->nullable();
            $table->text('apto_otros_procesos')->nullable();
            $table->text('arbol_genealogico')->nullable();
            $table->text('atribucion_a_marketing')->nullable();
            $table->text('autorizacion_memoramdum_administrativo')->nullable();
            $table->text('autorizacion_para_certificado_cil')->nullable();
            $table->text('autorizacion_para_subsanacion')->nullable();
            $table->text('autorizacion_recurso_de_alzada')->nullable();
            $table->text('calle')->nullable();
            $table->integer('cantidad_hijos_alzada')->nullable();
            $table->text('captador')->nullable();
            $table->text('carta_motivada')->nullable();
            $table->text('carta_motivada__pendiente_por_revision_')->nullable();
            $table->text('carta_motivada__sin_corregir_')->nullable();
            $table->text('caso_especial')->nullable();
            $table->text('categoria_segun_la_edad')->nullable();
            $table->text('ccse')->nullable();
            $table->text('ccse_archivado_espana')->nullable();
            $table->text('ccse_resultado')->nullable();
            $table->text('certificado_cil')->nullable();
            $table->text('certificado_de_estudio_simple')->nullable();
            $table->text('cif')->nullable();
            $table->text('city')->nullable();
            $table->text('ciudad_destino')->nullable();
            $table->text('ciudad_origen')->nullable();
            $table->text('clientes_formalizados_notificados')->nullable();
            $table->text('clientes_formalizados_sin_notificacion')->nullable();
            $table->text('cnat___declaracion_sust__de_docs_')->nullable();
            $table->text('codigo_consulta_ministerio')->nullable();
            $table->text('conyuge_interesado_en_proceso')->nullable();
            $table->text('coordinador')->nullable();
            $table->text('cuestionario_recurso_de_alzada')->nullable();
            $table->text('declaracion_cil')->nullable();
            $table->text('declaracion_de_emolumentos')->nullable();
            $table->text('declaracion_jurada_de_residencia')->nullable();
            $table->text('detalle_de_la_solicitud')->nullable();
            $table->text('direccion_en_el_pais_de_origen')->nullable();
            $table->text('documentos')->nullable();
            $table->text('documentos_adicionales')->nullable();
            $table->text('edad_ninos')->nullable();
            $table->text('edo_civil')->nullable();
            $table->text('ejecutivo_de_cartera')->nullable();
            $table->text('email_2')->nullable();
            $table->text('email_alternativo')->nullable();
            $table->text('etapa_de_ciclo_de_vida_sefar')->nullable();
            $table->text('etiquetas')->nullable();
            $table->text('fase_actual')->nullable();
            $table->text('fcje')->nullable();
            $table->text('fcje_familiar')->nullable();
            $table->text('fcje_madre')->nullable();
            $table->text('fcje_padre')->nullable();
            $table->date('fecha')->nullable();
            $table->date('fecha_caducidad_pasaporte')->nullable();
            $table->date('fecha_de_caducidad_del_pasaporte')->nullable();
            $table->text('fecha_de_confirmacion_del_cliente_como_recibido__juramentacion_')->nullable();
            $table->date('fecha_de_creacion_teamleader')->nullable();
            $table->date('fecha_de_firma')->nullable();
            $table->text('fecha_de_notificacion_al_cliente_por_email__juramentacion_')->nullable();
            $table->date('fecha_de_pago')->nullable();
            $table->date('fecha_de_retorno_mg_tours')->nullable();
            $table->date('fecha_de_salida_mg_tours')->nullable();
            $table->date('fecha_formalizacion__sistemas___no_tocar_')->nullable();
            $table->text('flexibilidad_mg_tours')->nullable();
            $table->text('gestoria_sefar__documentos_')->nullable();
            $table->text('grupo_familiar')->nullable();
            $table->text('identificacion_contable_del_cliente')->nullable();
            $table->integer('initial_zoom_webinar_attendance_average_duration')->nullable();
            $table->text('justificante_consignacion_fcje_r__de_alzada')->nullable();
            $table->text('justificante_memorandum_administrativo')->nullable();
            $table->text('justificante_ministerio_justicia__intencion_de_subsanar_')->nullable();
            $table->text('justificante_ministerio_justicia__subsanado_')->nullable();
            $table->text('justificante_recurso_de_alzada')->nullable();
            $table->text('justificante_resguardo_de_presentacion')->nullable();
            $table->text('justificante_subsanacion_de_vinculaciones')->nullable();
            $table->text('justificante_subsanacion_por_consanguinidad')->nullable();
            $table->text('literal_de_nacimiento_conyuge_espanol')->nullable();
            $table->text('n1__aacs_introducido_asociacion')->nullable();
            $table->text('n1__acta_notarial')->nullable();
            $table->date('n1__f__peticion_por_genealogia')->nullable();
            $table->date('n1__f__solicitado_por_genealogia')->nullable();
            $table->text('n2__aacs_notificacion_aprobado')->nullable();
            $table->date('n2__aiv_notificacion_aprobado')->nullable();
            $table->date('n2__f__de_solicitud_al_cliente')->nullable();
            $table->date('n2__f_solicitud_mayor_info')->nullable();
            $table->date('n2__fecha_aacs_notificacion_aprobado')->nullable();
            $table->text('n3__estatus_de_nacionalidad')->nullable();
            $table->date('n3__f___recordatorio_filiacion')->nullable();
            $table->date('n3__fcje_registro')->nullable();
            $table->date('n3__fecha_de_recordatorio')->nullable();
            $table->text('n4__aacs_retirado_asociacion')->nullable();
            $table->date('n4__f__entregado_genealogia')->nullable();
            $table->date('n4__f__enviada_a_genealogia')->nullable();
            $table->date('n4__fcje_certifi__descargado')->nullable();
            $table->text('n4__otros_nombres')->nullable();
            $table->date('n5__fecha_de_registro')->nullable();
            $table->text('n6__aacs_recibido_en_espana')->nullable();
            $table->text('n6__aiv_recibido_en_espana')->nullable();
            $table->text('nacionalidad_solicitada')->nullable();
            $table->text('no_de_iban')->nullable();
            $table->text('no_de_identificacion_nacional__nif_')->nullable();
            $table->text('nombre_completo_del_conyuge')->nullable();
            $table->text('nombre_completo_del_tutor_o_representante_legal')->nullable();
            $table->text('nombre_en_pasaporte')->nullable();
            $table->text('nombre_y_apellidos_del_solicitante')->nullable();
            $table->text('nombres_y_apellidos_de_madre')->nullable();
            $table->text('nombres_y_apellidos_del_padre')->nullable();
            $table->integer('nro__personas_a_registrar')->nullable();
            $table->integer('nro__personas_a_solicitar_el_recurso')->nullable();
            $table->text('numero')->nullable();
            $table->integer('numero_de_adultos')->nullable();
            $table->text('numero_de_expediente')->nullable();
            $table->integer('numero_de_ninos')->nullable();
            $table->text('numero_de_pasaporte_del_tutor_o_representante_legal')->nullable();
            $table->text('otros_servicios___mg_tours')->nullable();
            $table->text('pagos_completos')->nullable();
            $table->text('pagos_incompletos')->nullable();
            $table->text('pais_de_expedicion_del_pasaporte')->nullable();
            $table->text('pais_de_residencia')->nullable();
            $table->text('pais_destino')->nullable();
            $table->text('pais_origen')->nullable();
            $table->text('pais_ubicacion_mg_tours')->nullable();
            $table->text('paises_donde_ha_residido_en_los_ultimos_5_anos')->nullable();
            $table->text('partida_de_matrimonio_apostillada')->nullable();
            $table->text('partida_de_matrimonio_compulsada')->nullable();
            $table->text('partida_de_matrimonio_de_padres')->nullable();
            $table->text('partida_de_matrimonio_espana')->nullable();
            $table->text('partida_de_matrimonio_simple')->nullable();
            $table->text('partida_de_matrimonio_simple__')->nullable();
            $table->text('partida_de_nacimiento_apostillada')->nullable();
            $table->text('partida_de_nacimiento_compulsada')->nullable();
            $table->text('partida_de_nacimiento_en_formato_digital')->nullable();
            $table->text('partida_de_nacimiento_hijos_menores')->nullable();
            $table->text('partida_de_nacimiento_madre_apostillada')->nullable();
            $table->text('partida_de_nacimiento_padre_apostillada')->nullable();
            $table->text('partida_de_nacimiento_simple')->nullable();
            $table->text('partida_de_nacimiento_simple__')->nullable();
            $table->text('partida_nacimiento_en_espana')->nullable();
            $table->text('pasaporte__documento_')->nullable();
            $table->text('pasaporte_apostillado')->nullable();
            $table->text('pasaporte_completo')->nullable();
            $table->text('pasaporte_compulsado')->nullable();
            $table->text('pasaporte_habla_no_hispana')->nullable();
            $table->text('pasaporte_nacionalidad')->nullable();
            $table->text('pasaporte_simple_o_cedula')->nullable();
            $table->text('persona_encargada_de_la_toma_de_decisiones')->nullable();
            $table->text('plantilla_interna_carta_de_naturaleza')->nullable();
            $table->text('plantilla_interna_del_ministerio')->nullable();
            $table->text('poder_apostillado')->nullable();
            $table->text('poder_compulsado')->nullable();
            $table->text('poder_entre_tutores')->nullable();
            $table->text('poder_general_para_pleitos')->nullable();
            $table->text('poder_notariado_consulado')->nullable();
            $table->text('poder_notariado_espana')->nullable();
            $table->text('prioridad')->nullable();
            $table->text('profesion')->nullable();
            $table->text('provincia')->nullable();
            $table->text('puntuacion_coordinadores')->nullable();
            $table->text('registro_de_nacimiento')->nullable();
            $table->text('requerimientos_de_viaje')->nullable();
            $table->text('requiere_tutor_o_representante_legal_')->nullable();
            $table->text('resguardo_ccse')->nullable();
            $table->text('resguardo_dele')->nullable();
            $table->text('resolucion_denegatoria')->nullable();
            $table->text('retirado')->nullable();
            $table->text('servicio_pagado')->nullable();
            $table->text('servicio_solicitado___gestion_documental')->nullable();
            $table->text('servicio_solicitado__contacto_')->nullable();
            $table->text('servicio_solicitado__otros_')->nullable();
            $table->text('servicio_traduccion_ap__sefar_')->nullable();
            $table->text('sin_cita_ccse')->nullable();
            $table->text('sugerencias_mg_tours')->nullable();
            $table->text('supervisor_de_ventas')->nullable();
            $table->text('tipo_de_cupones')->nullable();
            $table->text('tipo_de_pasajero')->nullable();
            $table->text('tipo_de_servicio_mg_tours')->nullable();
            $table->text('tipo_de_visa_a_solicitar')->nullable();
            $table->text('total_a_facturar')->nullable();
            $table->integer('veces_casado')->nullable();
        });
    }

    /**
     * Revertir la migración.
     */
    public function down(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn([
                'aacs_madre',
                'aacs_padre',
                'acta_de_divorcio',
                'address',
                'adjuntar_archivo_de_comprobante_de_pago',
                'anos_en_residencia_actual',
                'antecedentes_penales_apostillada',
                'apellido_de_casada',
                'apto_otros_procesos',
                'arbol_genealogico',
                'atribucion_a_marketing',
                'autorizacion_memoramdum_administrativo',
                'autorizacion_para_certificado_cil',
                'autorizacion_para_subsanacion',
                'autorizacion_recurso_de_alzada',
                'calle',
                'cantidad_hijos_alzada',
                'captador',
                'carta_motivada',
                'carta_motivada__pendiente_por_revision_',
                'carta_motivada__sin_corregir_',
                'caso_especial',
                'categoria_segun_la_edad',
                'ccse',
                'ccse_archivado_espana',
                'ccse_resultado',
                'certificado_cil',
                'certificado_de_estudio_simple',
                'cif',
                'city',
                'ciudad_destino',
                'ciudad_origen',
                'clientes_formalizados_notificados',
                'clientes_formalizados_sin_notificacion',
                'cnat___declaracion_sust__de_docs_',
                'codigo_consulta_ministerio',
                'conyuge_interesado_en_proceso',
                'coordinador',
                'cuestionario_recurso_de_alzada',
                'declaracion_cil',
                'declaracion_de_emolumentos',
                'declaracion_jurada_de_residencia',
                'detalle_de_la_solicitud',
                'direccion_en_el_pais_de_origen',
                'documentos',
                'documentos_adicionales',
                'edad_ninos',
                'edo_civil',
                'ejecutivo_de_cartera',
                'email_2',
                'email_alternativo',
                'etapa_de_ciclo_de_vida_sefar',
                'etiquetas',
                'fase_actual',
                'fcje',
                'fcje_familiar',
                'fcje_madre',
                'fcje_padre',
                'fecha',
                'fecha_caducidad_pasaporte',
                'fecha_de_caducidad_del_pasaporte',
                'fecha_de_confirmacion_del_cliente_como_recibido__juramentacion_',
                'fecha_de_creacion_teamleader',
                'fecha_de_firma',
                'fecha_de_notificacion_al_cliente_por_email__juramentacion_',
                'fecha_de_pago',
                'fecha_de_retorno_mg_tours',
                'fecha_de_salida_mg_tours',
                'fecha_formalizacion__sistemas___no_tocar_',
                'flexibilidad_mg_tours',
                'gestoria_sefar__documentos_',
                'grupo_familiar',
                'identificacion_contable_del_cliente',
                'initial_zoom_webinar_attendance_average_duration',
                'justificante_consignacion_fcje_r__de_alzada',
                'justificante_memorandum_administrativo',
                'justificante_ministerio_justicia__intencion_de_subsanar_',
                'justificante_ministerio_justicia__subsanado_',
                'justificante_recurso_de_alzada',
                'justificante_resguardo_de_presentacion',
                'justificante_subsanacion_de_vinculaciones',
                'justificante_subsanacion_por_consanguinidad',
                'literal_de_nacimiento_conyuge_espanol',
                'n1__aacs_introducido_asociacion',
                'n1__acta_notarial',
                'n1__f__peticion_por_genealogia',
                'n1__f__solicitado_por_genealogia',
                'n2__aacs_notificacion_aprobado',
                'n2__aiv_notificacion_aprobado',
                'n2__f__de_solicitud_al_cliente',
                'n2__f_solicitud_mayor_info',
                'n2__fecha_aacs_notificacion_aprobado',
                'n3__estatus_de_nacionalidad',
                'n3__f___recordatorio_filiacion',
                'n3__fcje_registro',
                'n3__fecha_de_recordatorio',
                'n4__aacs_retirado_asociacion',
                'n4__f__entregado_genealogia',
                'n4__f__enviada_a_genealogia',
                'n4__fcje_certifi__descargado',
                'n4__otros_nombres',
                'n5__fecha_de_registro',
                'n6__aacs_recibido_en_espana',
                'n6__aiv_recibido_en_espana',
                'nacionalidad_solicitada',
                'no_de_iban',
                'no_de_identificacion_nacional__nif_',
                'nombre_completo_del_conyuge',
                'nombre_completo_del_tutor_o_representante_legal',
                'nombre_en_pasaporte',
                'nombre_y_apellidos_del_solicitante',
                'nombres_y_apellidos_de_madre',
                'nombres_y_apellidos_del_padre',
                'nro__personas_a_registrar',
                'nro__personas_a_solicitar_el_recurso',
                'numero',
                'numero_de_adultos',
                'numero_de_expediente',
                'numero_de_ninos',
                'numero_de_pasaporte_del_tutor_o_representante_legal',
                'otros_servicios___mg_tours',
                'pagos_completos',
                'pagos_incompletos',
                'pais_de_expedicion_del_pasaporte',
                'pais_de_residencia',
                'pais_destino',
                'pais_origen',
                'pais_ubicacion_mg_tours',
                'paises_donde_ha_residido_en_los_ultimos_5_anos',
                'partida_de_matrimonio_apostillada',
                'partida_de_matrimonio_compulsada',
                'partida_de_matrimonio_de_padres',
                'partida_de_matrimonio_espana',
                'partida_de_matrimonio_simple',
                'partida_de_matrimonio_simple__',
                'partida_de_nacimiento_apostillada',
                'partida_de_nacimiento_compulsada',
                'partida_de_nacimiento_en_formato_digital',
                'partida_de_nacimiento_hijos_menores',
                'partida_de_nacimiento_madre_apostillada',
                'partida_de_nacimiento_padre_apostillada',
                'partida_de_nacimiento_simple',
                'partida_de_nacimiento_simple__',
                'partida_nacimiento_en_espana',
                'pasaporte__documento_',
                'pasaporte_apostillado',
                'pasaporte_completo',
                'pasaporte_compulsado',
                'pasaporte_habla_no_hispana',
                'pasaporte_nacionalidad',
                'pasaporte_simple_o_cedula',
                'persona_encargada_de_la_toma_de_decisiones',
                'plantilla_interna_carta_de_naturaleza',
                'plantilla_interna_del_ministerio',
                'poder_apostillado',
                'poder_compulsado',
                'poder_entre_tutores',
                'poder_general_para_pleitos',
                'poder_notariado_consulado',
                'poder_notariado_espana',
                'prioridad',
                'profesion',
                'provincia',
                'puntuacion_coordinadores',
                'registro_de_nacimiento',
                'requerimientos_de_viaje',
                'requiere_tutor_o_representante_legal_',
                'resguardo_ccse',
                'resguardo_dele',
                'resolucion_denegatoria',
                'retirado',
                'servicio_pagado',
                'servicio_solicitado___gestion_documental',
                'servicio_solicitado__contacto_',
                'servicio_solicitado__otros_',
                'servicio_traduccion_ap__sefar_',
                'sin_cita_ccse',
                'sugerencias_mg_tours',
                'supervisor_de_ventas',
                'tipo_de_cupones',
                'tipo_de_pasajero',
                'tipo_de_servicio_mg_tours',
                'tipo_de_visa_a_solicitar',
                'total_a_facturar',
                'veces_casado',
            ]);
        });
    }
};
