<?php

return [
    'category' => 'banca_online_2026',
    'source' => 'banca_online_2026',

    'countries' => [
        'espana' => [
            'label' => 'Espana',
            'service_name' => 'Española Sefardi',
            'stripe_account' => 'default',
            'seed_catalog' => true,
            'public_enabled' => true,
        ],
        'portugal' => [
            'label' => 'Portugal',
            'service_name' => 'Portuguesa Sefardi',
            'stripe_account' => 'portugal',
            'seed_catalog' => false,
            'public_enabled' => false,
        ],
        'italia' => [
            'label' => 'Italia',
            'service_name' => 'Italiana',
            'stripe_account' => 'default',
            'seed_catalog' => false,
            'public_enabled' => false,
        ],
    ],

    'packages' => [
        'regular' => [
            'title' => 'Regular',
            'summary' => 'La cobertura esencial para avanzar con una estrategia definida.',
            'recommended' => false,
            'order' => 1,
        ],
        'medium' => [
            'title' => 'Medium',
            'summary' => 'Una cobertura ampliada con mayor acompañamiento durante el proceso.',
            'recommended' => true,
            'order' => 2,
        ],
        'premium' => [
            'title' => 'Premium',
            'summary' => 'La cobertura más completa para escenarios que requieren máxima atención.',
            'recommended' => false,
            'order' => 3,
        ],
    ],

    'installments' => [
        'periods' => [
            'monthly' => [
                'label' => 'Mensual',
                'plural_label' => 'mensuales',
                'enabled' => true,
                'surcharge_percent' => 0,
                'stripe_interval' => 'month',
                'stripe_interval_count' => 1,
                'start_after_days' => null,
            ],
            'quarterly' => [
                'label' => 'Trimestral',
                'plural_label' => 'trimestrales',
                'enabled' => true,
                'surcharge_percent' => 0,
                'stripe_interval' => 'month',
                'stripe_interval_count' => 3,
                'start_after_days' => null,
            ],
            'semimonthly' => [
                'label' => 'Cada medio mes',
                'plural_label' => 'cada medio mes',
                'enabled' => true,
                'surcharge_percent' => 0,
                'stripe_interval' => 'day',
                'stripe_interval_count' => 15,
                'start_after_days' => 15,
            ],
            'annual' => [
                'label' => 'Anual',
                'plural_label' => 'anuales',
                'enabled' => true,
                'surcharge_percent' => 0,
                'stripe_interval' => 'year',
                'stripe_interval_count' => 1,
                'start_after_days' => null,
            ],
        ],
        'initial_rules' => [
            ['min_initial_percent' => 20, 'max_installments' => 12],
            ['min_initial_percent' => 35, 'max_installments' => 9],
            ['min_initial_percent' => 50, 'max_installments' => 6],
            ['min_initial_percent' => 70, 'max_installments' => 3],
        ],
    ],

    'plans' => [
        'solicitud-estrategica' => [
            'enabled' => true,
            'title' => 'Solicitud estrategica de nacionalidad',
            'short_title' => 'Solicitud estrategica',
            'summary' => 'Fase legal y fase genealogica configurables en una sola contratacion.',
            'public_title' => 'Plan de Solicitud Estrategica de Nacionalidad Española por Origen Sefardi',
            'eyebrow' => 'Primera ruta estrategica',
            'intro' => 'Inicia tu camino con una estrategia integral que combina el rigor genealogico y juridico desde el primer paso.',
            'highlights' => [
                'Plan Estrategico Genealogico.',
                'Plan Estrategico Juridico.',
                'Preparacion, formalizacion y subsanacion cuando corresponda.',
            ],
            'action' => 'Ver estrategia de solicitud',
            'service_scope' => ['espana', 'portugal', 'italia'],
            'packages' => [
                'regular' => [
                    'title' => 'Plan Estrategico Esencial',
                    'summary' => 'Cobertura esencial para preparar, formalizar y sostener la solicitud estrategica.',
                    'list_price' => 10910,
                    'price' => 8311,
                    'saving' => 2599,
                    'show_component_prices' => false,
                    'features' => [
                        'Definicion de la via seleccionada',
                        'Organizacion documental',
                        'Solicitud de documentos juridicos',
                        'Preparacion de anexos',
                        'Formalizacion',
                        'Consulta con facilitador',
                        'Construccion de hipotesis genealogica',
                        'Construccion de arbol interno',
                        'Localizacion documental',
                        'Solicitud de documentos',
                        'Asistencia documental genealogica, si se requiere',
                        'Contraste de evidencias',
                        'Preparacion del expediente en la plataforma del ente certificador',
                        'Presentacion ante entidad certificadora',
                        'Respuesta a requerimientos',
                        'Incorporacion de nuevas evidencias',
                    ],
                ],
                'medium' => [
                    'title' => 'Plan Estrategico Recomendado',
                    'summary' => 'La alternativa recomendada para casos que requieren mayor defensa documental y juridica.',
                    'list_price' => 13646,
                    'price' => 10233,
                    'saving' => 3413,
                    'show_component_prices' => false,
                    'features' => [
                        'Definicion de la via seleccionada',
                        'Organizacion documental',
                        'Solicitud de documentos juridicos',
                        'Preparacion de anexos',
                        'Formalizacion',
                        'Consulta con facilitador',
                        'Construccion de hipotesis genealogica',
                        'Construccion de arbol interno',
                        'Localizacion documental',
                        'Solicitud de documentos',
                        'Asistencia documental genealogica, si se requiere',
                        'Contraste de evidencias',
                        'Preparacion del expediente en la plataforma del ente certificador',
                        'Presentacion ante entidad certificadora',
                        'Respuesta a requerimientos',
                        'Incorporacion de nuevas evidencias',
                        '3 escritos adicionales',
                        'Copia de constancias de formalizacion',
                        '1 consulta juridica',
                        '1 dictamen de derecho genealogista',
                        '6 requerimientos',
                        'Copia de certificado FCJE - CIL con marca de agua',
                    ],
                ],
                'premium' => [
                    'title' => 'Plan Estrategico Pro Ultra',
                    'summary' => 'La cobertura mas completa para expedientes que requieren maxima defensa y seguimiento.',
                    'list_price' => 16346,
                    'price' => 10625,
                    'saving' => 5721,
                    'show_component_prices' => false,
                    'features' => [
                        'Definicion de la via seleccionada',
                        'Organizacion documental',
                        'Solicitud de documentos juridicos',
                        'Preparacion de anexos',
                        'Formalizacion',
                        'Consulta con facilitador',
                        'Construccion de hipotesis genealogica',
                        'Construccion de arbol interno',
                        'Localizacion documental',
                        'Solicitud de documentos',
                        'Asistencia documental genealogica, si se requiere',
                        'Contraste de evidencias',
                        'Preparacion del expediente en la plataforma del ente certificador',
                        'Presentacion ante entidad certificadora',
                        'Respuesta a requerimientos',
                        'Incorporacion de nuevas evidencias',
                        '5 escritos adicionales',
                        'Copia de constancias de formalizacion',
                        '3 consultas juridicas',
                        '12 requerimientos',
                        'Copia de certificado FCJE - CIL con marca de agua',
                    ],
                ],
            ],
            'sections' => [
                [
                    'title' => 'Fase legal',
                    'summary' => 'Solicitud ante el Estado correspondiente y armado juridico del expediente.',
                    'items' => [
                        ['slug' => 'creacion-expediente-juridico', 'name' => 'Creacion del expediente juridico', 'price' => 0, 'required' => true, 'default_selected' => true],
                        ['slug' => 'creacion-expediente-familiar', 'name' => 'Creacion del expediente familiar', 'price' => 0, 'required' => true, 'default_selected' => true],
                        ['slug' => 'analisis-intuitu-personae', 'name' => 'Analisis Intuitu Personae del linaje', 'price' => 0, 'required' => true, 'default_selected' => true],
                        ['slug' => 'desarrollo-argumental', 'name' => 'Desarrollo argumental de la solicitud juridico-administrativa', 'price' => 0, 'required' => true, 'default_selected' => true],
                        ['slug' => 'revision-cotejo-probatorio', 'name' => 'Revision y cotejo del material probatorio', 'price' => 0, 'required' => true, 'default_selected' => true],
                        ['slug' => 'formalizacion-expediente', 'name' => 'Formalizacion del expediente', 'price' => 0],
                        ['slug' => 'formalizacion-express-expediente', 'name' => 'Formalizacion express del expediente', 'price' => 0, 'group' => 'formalizacion'],
                        ['slug' => 'una-subsanacion-legal', 'name' => '1 subsanacion', 'price' => 575, 'group' => 'subsanaciones-legales'],
                        ['slug' => 'dos-subsanaciones-legales', 'name' => '2 subsanaciones', 'price' => 0, 'group' => 'subsanaciones-legales'],
                        ['slug' => 'tres-subsanaciones-legales', 'name' => '3 subsanaciones', 'price' => 0, 'group' => 'subsanaciones-legales'],
                        ['slug' => 'una-consulta-abogado', 'name' => '1 consulta con un abogado', 'price' => 275, 'group' => 'consultas-abogado'],
                        ['slug' => 'dos-consultas-abogado', 'name' => '2 consultas con un abogado', 'price' => 550, 'group' => 'consultas-abogado'],
                        ['slug' => 'tres-consultas-abogado', 'name' => '3 consultas con un abogado', 'price' => 725, 'group' => 'consultas-abogado'],
                    ],
                ],
                [
                    'title' => 'Fase genealogica',
                    'summary' => 'Trabajo ante la FCJE y soporte documental genealogico.',
                    'items' => [
                        ['slug' => 'creacion-expediente-genealogico', 'name' => 'Creacion del expediente genealogico', 'price' => 0],
                        ['slug' => 'revision-linea-documentacion', 'name' => 'Revision y cotejo de la linea y documentacion genealogica probatoria', 'price' => 0],
                        ['slug' => 'redaccion-informe-genealogico', 'name' => 'Redaccion del informe genealogico', 'price' => 0],
                        ['slug' => 'perfil-digital-fcje', 'name' => 'Creacion del perfil digital en la plataforma de la FCJE', 'price' => 0],
                        ['slug' => 'carga-informe-fcje', 'name' => 'Carga del informe genealogico y sus documentos ante la FCJE', 'price' => 0],
                        ['slug' => 'donativo-inicial', 'name' => 'Pago del donativo inicial', 'price' => 0],
                        ['slug' => 'documento-tramitacion-fcje', 'name' => 'Documento de tramitacion de la FCJE', 'price' => 0],
                        ['slug' => 'defensa-tres-requerimientos', 'name' => 'Defensa de genealogia ante la FCJE: 3 requerimientos', 'price' => 0, 'group' => 'requerimientos-fcje'],
                        ['slug' => 'defensa-seis-requerimientos', 'name' => 'Defensa de genealogia ante la FCJE: 6 requerimientos', 'price' => 0, 'group' => 'requerimientos-fcje'],
                        ['slug' => 'defensa-doce-requerimientos', 'name' => 'Defensa de genealogia ante la FCJE: 12 requerimientos', 'price' => 0, 'group' => 'requerimientos-fcje'],
                        ['slug' => 'aprobacion-certificado-donativo-final', 'name' => 'Obtencion de aprobacion del certificado y pago del donativo final', 'price' => 0],
                        ['slug' => 'carga-certificado-expediente', 'name' => 'Recepcion y carga del certificado al expediente juridico', 'price' => 0],
                        ['slug' => 'copia-certificado-fcje', 'name' => 'Copia del certificado de la FCJE', 'price' => 0],
                    ],
                ],
            ],
        ],

        'administrativo' => [
            'enabled' => true,
            'title' => 'Plan estrategico administrativo',
            'short_title' => 'Administrativo',
            'summary' => 'Subsanaciones, mejoras y recursos administrativos despues de la formalizacion.',
            'public_title' => 'Plan Estrategico Administrativo',
            'eyebrow' => 'Segunda ruta estrategica',
            'intro' => 'Diseñado para maximizar tus posibilidades de exito en via administrativa con estrategia, seguimiento y presion juridica.',
            'highlights' => [
                'Analisis y preparacion de escritos.',
                'Impulso y optimizacion del expediente.',
                'Acciones para forzar una decision estimatoria.',
            ],
            'action' => 'Activar estrategia administrativa',
            'service_scope' => ['espana', 'portugal', 'italia'],
            'packages' => [
                'regular' => [
                    'title' => 'Plan Administrativo Uno',
                    'summary' => 'Cobertura esencial para revisar, reforzar y defender el expediente en via administrativa.',
                    'list_price' => 5305,
                    'price' => 3205,
                    'saving' => 2100,
                    'show_component_prices' => false,
                    'features' => [
                        'Revision integral del expediente',
                        'Generacion de la estrategia de derecho genealogista',
                        'Incorporacion de los elementos y argumentos estrategicos en el expediente del representado',
                        'Recurso de alzada cuando corresponda',
                        'Revision del expediente y del recurso por 1 abogado y 1 genealogista',
                    ],
                ],
                'medium' => [
                    'title' => 'Plan Administrativo Dos',
                    'summary' => 'La alternativa recomendada para incorporar acciones adicionales y doble revision especializada.',
                    'list_price' => 6427,
                    'price' => 4007,
                    'saving' => 2420,
                    'show_component_prices' => false,
                    'features' => [
                        'Revision integral del expediente',
                        'Generacion de la estrategia de derecho genealogista',
                        'Incorporacion de los elementos y argumentos estrategicos en el expediente del representado',
                        'Recurso de alzada cuando corresponda',
                        '1 solicitud de resolucion expresa',
                        '1 subsanacion',
                        '1 mejora documental',
                        '1 introduccion de prueba adicional',
                        '1 impulso administrativo',
                        '1 consulta juridica',
                        'Revision del expediente y del recurso por 2 abogados y 2 genealogistas',
                    ],
                ],
                'premium' => [
                    'title' => 'Plan Administrativo Tres',
                    'summary' => 'La cobertura mas completa para expedientes que requieren mayor insistencia documental y juridica.',
                    'list_price' => 7319,
                    'price' => 4521,
                    'saving' => 2798,
                    'show_component_prices' => false,
                    'features' => [
                        'Revision integral del expediente',
                        'Generacion de la estrategia de derecho genealogista',
                        'Incorporacion de los elementos y argumentos estrategicos en el expediente del representado',
                        'Recurso de alzada cuando corresponda',
                        'Solicitud de resolucion expresa',
                        '3 subsanaciones',
                        '3 mejoras documentales',
                        '3 introducciones de prueba adicional',
                        '3 impulsos administrativos',
                        '3 consultas juridicas',
                        'Revision del expediente y del recurso por 2 abogados y 2 genealogistas',
                        'Copia de constancias cuando corresponda',
                    ],
                ],
            ],
            'sections' => [
                [
                    'title' => 'Despues de la formalizacion',
                    'summary' => 'Acciones administrativas para sostener o reforzar el expediente.',
                    'items' => [
                        ['slug' => 'una-subsanacion-expediente', 'name' => '1 subsanacion del expediente', 'price' => 0, 'group' => 'subsanaciones-expediente'],
                        ['slug' => 'dos-subsanaciones-expediente', 'name' => '2 subsanaciones del expediente', 'price' => 0, 'group' => 'subsanaciones-expediente'],
                        ['slug' => 'tres-subsanaciones-expediente', 'name' => '3 subsanaciones del expediente', 'price' => 0, 'group' => 'subsanaciones-expediente'],
                        ['slug' => 'una-mejora-expediente', 'name' => '1 mejora del expediente', 'price' => 0, 'group' => 'mejoras-expediente'],
                        ['slug' => 'dos-mejoras-expediente', 'name' => '2 mejoras del expediente', 'price' => 0, 'group' => 'mejoras-expediente'],
                        ['slug' => 'tres-mejoras-expediente', 'name' => '3 mejoras del expediente', 'price' => 0, 'group' => 'mejoras-expediente'],
                        ['slug' => 'recurso-resolucion-expresa', 'name' => 'Recurso de solicitud de resolucion expresa', 'price' => 0],
                        ['slug' => 'recurso-alzada-silencio', 'name' => 'Recurso de alzada por silencio administrativo', 'price' => 0],
                    ],
                ],
            ],
        ],

        'judicial' => [
            'enabled' => true,
            'title' => 'Plan estrategico judicial',
            'short_title' => 'Judicial',
            'summary' => 'Recurso contencioso administrativo, pendiente de desglose operativo.',
            'public_title' => 'Plan Estrategico Judicial',
            'eyebrow' => 'Tercera ruta estrategica',
            'intro' => 'Si la via administrativa no prospera, activamos la via judicial con la maxima solidez y estrategia procesal.',
            'highlights' => [
                'Preparacion de la demanda.',
                'Introduccion del escrito.',
                'Seguimiento, impulso e informes complementarios.',
            ],
            'action' => 'Activar estrategia judicial',
            'service_scope' => ['espana', 'portugal', 'italia'],
            'packages' => [
                'regular' => [
                    'title' => 'Plan Judicial Uno',
                    'summary' => 'Cobertura esencial para preparar y presentar la via judicial.',
                    'list_price' => 5685,
                    'price' => 3489,
                    'saving' => 2196,
                    'show_component_prices' => false,
                    'features' => [
                        'Analisis juridico',
                        'Redaccion de escrito',
                        'Preparacion de demanda',
                        'Presentacion judicial',
                    ],
                ],
                'medium' => [
                    'title' => 'Plan Judicial Dos',
                    'summary' => 'Cobertura judicial ampliada con pruebas adicionales y recurso judicial.',
                    'list_price' => 6721,
                    'price' => 4235,
                    'saving' => 2486,
                    'show_component_prices' => false,
                    'features' => [
                        'Analisis juridico',
                        'Redaccion de escrito',
                        'Preparacion de demanda',
                        'Presentacion judicial',
                        'Presentacion de pruebas adicionales (hasta 2 pruebas)',
                        'Recursos judiciales (hasta 1)',
                    ],
                ],
                'premium' => [
                    'title' => 'Plan Judicial Tres',
                    'summary' => 'La cobertura judicial mas completa con pruebas, recursos, vistas y asistencia.',
                    'list_price' => 7727,
                    'price' => 4973,
                    'saving' => 2754,
                    'show_component_prices' => false,
                    'features' => [
                        'Analisis juridico',
                        'Redaccion de escrito',
                        'Preparacion de demanda',
                        'Presentacion judicial',
                        'Presentacion de pruebas adicionales (hasta 4 pruebas)',
                        'Recursos judiciales (hasta 3)',
                        'Preparacion de vistas',
                        'Asistencia a vistas',
                    ],
                ],
            ],
            'sections' => [
                [
                    'title' => 'Accion judicial',
                    'summary' => 'Recurso judicial asociado al expediente.',
                    'items' => [
                        ['slug' => 'recurso-contencioso-administrativo', 'name' => 'Recurso contencioso administrativo', 'price' => 0],
                    ],
                ],
            ],
        ],

        'reforzamiento-seguro' => [
            'enabled' => false,
            'title' => 'Plan estrategico de reforzamiento y seguro',
            'short_title' => 'Reforzamiento y seguro',
            'summary' => 'Analisis preventivo para cubrir un eventual cambio de linea.',
            'service_scope' => ['espana', 'portugal', 'italia'],
            'sections' => [
                [
                    'title' => 'Cambio de linea',
                    'summary' => 'Reserva estrategica para escenarios donde el caso requiera cambio de linea.',
                    'items' => [
                        ['slug' => 'un-analisis-cambio-linea', 'name' => '1 analisis de cambio de linea', 'price' => 0, 'group' => 'cambio-linea'],
                        ['slug' => 'dos-analisis-cambio-linea', 'name' => '2 analisis de cambio de linea', 'price' => 0, 'group' => 'cambio-linea'],
                        ['slug' => 'tres-analisis-cambio-linea', 'name' => '3 analisis de cambio de linea', 'price' => 0, 'group' => 'cambio-linea'],
                    ],
                ],
            ],
        ],
    ],
];
